name: 'Docker Build and Push'
description: 'Builds and pushes Docker images to GitHub Container Registry'

inputs:
  imageName:
    description: 'Name of the image to build and push'
    required: true
  dockerFile:
    description: 'Filepath relative to the repository root'
    required: true
  user:
    description: 'User name used for ghcr'
    required: true
  password:
    description: 'Password for user when logging in to ghcr'
    required: true
outputs:
  imageTag:
    description: 'The tag of the built Docker image'
    value: ghcr.io/${{ github.repository_owner }}/${{ inputs.imageName }}
runs:
  using: 'composite'
  steps:
    - name: Set up environment variables
      shell: bash
      run: echo "FULL_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ inputs.imageName }}" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      shell: bash
      run: docker login ghcr.io -u ${{ inputs.user }} -p ${{ inputs.password }}

    - name: Check if Docker image exists
      id: check_image
      shell: bash
      run: |
        if docker manifest inspect $FULL_IMAGE_NAME; then
          echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
        else
          echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Build Docker image
      if: env.IMAGE_EXISTS == 'false'
      shell: bash
      run: docker build -t $FULL_IMAGE_NAME -f ${{ inputs.dockerFile }} .

    - name: Push Docker image
      if: env.IMAGE_EXISTS == 'false'
      shell: bash
      run: docker push $FULL_IMAGE_NAME 

